apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: nd50nxydl-go 
  janus-idp.io/tekton: nd50nxydl-go
  backstage.io/kubernetes-id: nd50nxydl-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nd50nxydl-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml