apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nd50nxydl-go
  janus-idp.io/tekton: nd50nxydl-go
  backstage.io/kubernetes-id: nd50nxydl-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nd50nxydl-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
