apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nd50nxydl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nd50nxydl-go 
  name: nd50nxydl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nd50nxydl-go 
